
# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_state\
# $git_status\
# $git_metrics\
# $fill\
# $python\
# $terraform\
# $kubernetes\
# $line_break\
# $character"""

format = """
$username\
$hostname\
$directory\
$character"""

right_format = """
$git_branch\
$git_state\
$git_status\
$git_metrics\
$python\
$terraform\
$kubernetes"""

add_newline = false


[fill]
symbol = " "

[directory]
style = "blue"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[username]
disabled = false
format = "[$user]($style)"

[hostname]
disabled = false
format = "[@$hostname]($style) "

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[kubernetes]
disabled=false
symbol =	"☸ "
format = '[$symbol$cluster]($style) '
style = "cyan"

[python]
disabled=false
format='[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[terraform]
disabled=false
format="[$symbol$version]($style) "

[rust]
symbol = " "
