# Helix Editor Config
# https://helix-editor.com/

theme = "onedark"

[editor]
line-number = "relative"
bufferline = "always"
true-color = true
cursorline = true
# rulers = [80]
color-modes =  true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spinner","file-name","file-modification-indicator"]
center = []
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true
wrap-at-text-width = true
wrap-indicator = ""
